#!/bin/bash 

# check the packge and feed right url for the bash sript
# https://github.com/nodesource/distributions/blob/master/README.md#user-content-enterprise-linux-based-distributions

# (@Repo)
if [[ -z "$1" && $1 == "https://rpm.nodesource.com/setup"* ]]; then
    sudo yum erase nodejs -y
    curl -sL "$1" | sudo -E bash -
    sudo yum install -y nodejs
fi

