#! /bin/sh 

REPOINFO="[vbatts-bazel]
name=Copr repo for bazel owned by vbatts
baseurl=https://copr-be.cloud.fedoraproject.org/results/vbatts/bazel/epel-7-$basearch/
type=rpm-md
skip_if_unavailable=True
gpgcheck=1
gpgkey=https://copr-be.cloud.fedoraproject.org/results/vbatts/bazel/pubkey.gpg
repo_gpgcheck=0
enabled=1
enabled_metadata=1"

bazelRepo () {
    printf "$REPOINFO" >/etc/yum.repos.d/Bazel.repo
}

REPOFILE='/etc/yum.repos.d/Bazel.repo'

if ! [ -e $REPOFILE ]; then
	bazelRepo
fi

sudo yum install bazel -y


